[postgres]
    container_name = "postgres_container"
    host = "localhost"
    port = 5432
    db = "postgres"
    user = "postgres"
    password = "postgres"
[redis]
    container_name = "redis_container"
