services:
  app:
    container_name: app_container
    build:
      context: .
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    ports:
      - "8000:8000"
    command: sh -c "poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
      - rabbitmq
      - redis
  worker:
    container_name: worker_container
    build:
      context: .
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    command: sh -c "poetry run celery -A src.worker.insert_parcel_celery worker --loglevel=info broker_connection_retry_on_startup=True"
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    container_name: redis_container
    image: redis
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      TZ: Europe/Moscow
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
      TZ: Europe/Moscow
      RABBITMQ_DEFAULT_VHOST: parcels
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
